### PR TITLE
updating per SPEC guide

### PR DESCRIPTION
**Pull request by dmiskovic-NV**
SPEC guide for PTD recommends use of Telnet commands ("RL") to grab power, rather that using ptd.log.
I made changes that should make process indistinguishable from previous process (spl.tx will still be created in ranging and run_1 folders), only change is the origin of that data

### CODE REVIEW

**Comment by dmiskovic-NV** [comment]
recheck

**Comment by dmiskovic-NV** [comment]
recheck

**Review by arjunsuresh — APPROVED** [review]
LGTM

**Comment by dmiskovic-NV** [comment]
apologies for the noise. mix of adding to wrong fork and formatting issues and some code pitfalls

**Review by araghun — APPROVED** [review]
Approved per alignment in 1/31 PowerWG

**Comment by s-idgunji** [comment]
Merged per our discussion in Power WG meeting  (Jan 31 2023)

**Pull request merged**
