### PR TITLE
Added Multi-analyzer Multi channel code - server.py and summary.py

### PR DESCRIPTION
**Pull request by pawanambalkar**
Added Multi analyzer and multi-channel code support for review and merge.This code will support only for Inference power methodology.  Details will be shared on the code and proposal via powerpoint in the power group meetings. Please reach out to power working group for any questions or me (Pawan Ambalkar).

### CODE REVIEW

**Review by araghun — DISMISSED** [review]
Reviewed in PowerWG 9/24.
Approve and Merge
No questions

**Comment by arjunsuresh** [comment]
recheck

**Comment by arjunsuresh** [comment]
recheck

**Review by pgmpablo157321 — APPROVED** [review]

**Review by araghun — APPROVED** [review]
As discussed in prior PowerWGs as well as on 11/12

**Pull request merged**
