### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manuprasad07**
Remove references to redundant flags (--send-logs and --fetch-logs) and to output directory on server.

### CODE REVIEW

**Comment by manuprasad07** [comment]
Recheck

**Comment by manuprasad07** [comment]
@araghun @s-idgunji FYI - PR for updated README file

**Comment by psyhtest** [comment]
@manuprasad07, thank you, LGTM. FWITW, I spent a good couple of hours grappling with the changes you updated the README for...

**Comment by araghun** [comment]
@s-idgunji : Can you merge this since it was @manuprasad07 you edited the ReadMe, I dont want to Merge it?

**Pull request merged**
