### PR TITLE
Reintroduce autoranging

### LINKED ISSUE #253: Yokogawa WT310E ranging failures at under 0.2 A
I'm investigating a very weird issue with the updated r1.1 workflow. It started with testing workflows on an Edge system. In the Offline scenario, the system power is over 24 Watts, and everything works as expected. In the Single Scenario, however, the system power is under 20 Watts, and I'm unable to take the measurements. Here's a typical failure log on the director side:

```
08-01-2021 10:56:59.225: WARNING: Uncertainty unknown for the last measurement sample! channel 0
ptd-server 2021-08-01 11:56:59,416 [INFO] Sending to ptd: 'Stop'
08-01-2021 10:56:59.417: Response to client sent: Stopping untimed measurement
ptd-server 2021-08-01 11:56:59,417 [INFO] Reply from ptd: 'Stopping untimed measurement'
ptd-server 2021-08-01 11:56:59,437 [ERROR] Got an exception
Traceback (most recent call last):
  File "/home/anton/projects/mlperf/power-dev-r1.1/ptd_client_server/../ptd_client_server/lib/server.py", line 577, in handle_connection
    reply = self._handle_cmd(cmd, p)
  File "/home/anton/projects/mlperf/power-dev-r1.1/ptd_client_server/../ptd_client_server/lib/server.py", line 650, in _handle_cmd                                     
    return unbool[self.session.stop(Mode.RANGING)]
  File "/home/anton/projects/mlperf/power-dev-r1.1/ptd_client_server/../ptd_client_server/lib/server.py", line 861, in stop                                                                                
    self._maxVolts, self._maxAmps = max_volts_amps(
  File "/home/anton/projects/mlperf/power-dev-r1.1/ptd_client_server/../ptd_client_server/lib/server.py", line 187, in max_volts_amps           
    raise MaxVoltsAmpsNegativeValuesError(f"Could not find values for {mark!r}")
ptd_client_server.lib.server.MaxVoltsAmpsNegativeValuesError: Could not find values for '2021-08-01_11-45-44_ranging'                                                                                      
ptd-server 2021-08-01 11:56:59,437 [INFO] Sending reply to client 'Error: exception'
ptd-server 2021-08-01 11:56:59,452 [INFO] Connection closed         
ptd-server 2021-08-01 11:56:59,452 [WARNING] Client connection closed unexpectedly
ptd-server 2021-08-01 11:56:59,452 [INFO] Sending to ptd: 'Stop'
08-01-2021 10:56:59.923: Completed test
08-01-2021 10:56:59.923: WARNING: No valid watts samples for this measurement!      
08-01-2021 10:56:59.924: Response to client sent: Error: no measurement to stop
ptd-server 2021-08-01 11:56:59,924 [INFO] Reply from ptd: 'Error: no measurement to stop'
ptd-server 2021-08-01 11:56:59,924 [INFO] Sending to ptd: 'SR,V,300.000000'
08-01-2021 10:56:59.924: Volt range set to 300.000000V
```

Here's how the PTDaemon log looks like on the director side:

```
me,08-01-2021 10:56:42.225,Watts,-22.100000,Volts,248.180000,Amps,-3.168000,PF,0.456200,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:43.226,Watts,-21.900000,Volts,248.130000,Amps,-3.168000,PF,0.454700,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:44.225,Watts,-21.300000,Volts,248.150000,Amps,-3.163000,PF,0.452500,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:45.225,Watts,-16.800000,Volts,248.130000,Amps,-3.130000,PF,0.427200,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:46.226,Watts,-16.000000,Volts,248.060000,Amps,-3.124000,PF,0.421700,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:47.225,Watts,-16.000000,Volts,248.140000,Amps,-3.125000,PF,0.422000,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:48.225,Watts,-15.700000,Volts,248.140000,Amps,-3.122000,PF,0.419100,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:49.226,Watts,-15.600000,Volts,248.170000,Amps,-3.121000,PF,0.417600,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:50.225,Watts,-15.500000,Volts,248.170000,Amps,-3.121000,PF,0.417300,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:51.225,Watts,-15.100000,Volts,248.090000,Amps,-3.118000,PF,0.413500,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:52.225,Watts,-15.200000,Volts,248.070000,Amps,-3.119000,PF,0.413400,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:53.225,Watts,-15.200000,Volts,248.110000,Amps,-3.119000,PF,0.413100,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:54.226,Watts,-15.200000,Volts,248.180000,Amps,-3.118000,PF,0.414100,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:55.225,Watts,-15.200000,Volts,248.220000,Amps,-3.119000,PF,0.414600,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:56.225,Watts,-15.200000,Volts,248.210000,Amps,-3.118000,PF,0.414400,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:57.226,Watts,-15.200000,Volts,248.230000,Amps,-3.118000,PF,0.415100,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:58.225,Watts,-15.200000,Volts,248.110000,Amps,-3.118000,PF,0.415300,Mark,2021-08-01_11-45-44_ranging
Time,08-01-2021 10:56:59.225,Watts,-15.200000,Volts,248.100000,Amps,-3.118000,PF,0.415200,Mark,2021-08-01_11-45-44_ranging
```
The power figures are negative but otherwise sensible. The Amps figures are negative and non-sensible.

### PR DESCRIPTION
**Pull request by psyhtest**
Fixes #253. Adding a new hash to the list of acceptable checksums allows submitters to use any commit on this r1.1 branch for v1.1 submission - both with max ranging (before this PR) and auto ranging (after this PR).

### CODE REVIEW

**Comment by s-idgunji** [comment]
Hi Anton  (@psyhtest ) -  Thanks.   How does one select max vs auto if both are supported ?  Or have we deprecated max with this ?

**Review by nvpohanh — APPROVED** [review]
LGTM.

**Comment by psyhtest** [comment]
Sachin (@s-idgunji) Every submitter needs to clone the [`r1.1`](https://github.com/mlcommons/power-dev/commits/r1.1) branch:

```
$ git clone https://github.com/mlcommons/power-dev/commits/r1.1 power-dev-r1.1
```

If they do it now:
- If they want to use auto ranging (the r1.0 behaviour and the new default behaviour), they should do nothing.
- If they want to use max ranging (the r1.1 behaviour at the time the random seeds got distributed), they should do "downgrade":
```
$ cd power-dev-r1.1
$ git checkout 020bd3cb33e
```
(`020bd3cb33e` is the hash of the last commit on the r1.1 branch with the max ranging behaviour.)

If they did it before today:
- If they want to use auto ranging, they should do "upgrade":
```
$ cd power-dev-r1.1
$ git pull
```
- If they want to use max ranging, they should do nothing.

Results obtained with either approach will be accepted by the checker. Does it make sense?

In the future, we should discuss having explicit options:
- Auto ranging (default)?
- Max ranging
- User-selected ranging (without the need for a ranging run).

**Comment by s-idgunji** [comment]
@psyhtest  Thanks for the write up It's likely  that some submitters have used versions prior to your changes last week, so we want to make sure that those submitters do not face issues due to the version used.  We can discuss this in our Power WG this week.  I'm not sure how many will "do it now" given we're 3 days away from submission , but we can discuss all options.

> Sachin (@s-idgunji) Every submitter needs to clone the [`r1.1`](https://github.com/mlcommons/power-dev/commits/r1.1) branch:
> 
> ```
> $ git clone https://github.com/mlcommons/power-dev/commits/r1.1 power-dev-r1.1
> ```
> 
> If they do it now:
> 
> * If they want to use auto ranging (the r1.0 behaviour and the new default behaviour), they should do nothing.
> * If they want to use max ranging (the r1.1 behaviour at the time the random seeds got distributed), they should do "downgrade":
> 
> ```
> $ cd power-dev-r1.1
> $ git checkout 020bd3cb33e
> ```
> 
> (`020bd3cb33e` is the hash of the last commit on the r1.1 branch with the max ranging behaviour.)
> 
> If they did it before today:
> 
> * If they want to use auto ranging, they should do "upgrade":
> 
> ```
> $ cd power-dev-r1.1
> $ git pull
> ```
> 
> * If they want to use max ranging, they should do nothing.
> 
> Results obtained with either approach will be accepted by the checker. Does it make sense?
> 
> In the future, we should discuss having explicit options:
> 
> * Auto ranging (default)?
> * Max ranging
> * User-selected ranging (without the need for a ranging run).

**Pull request merged**
